# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_serial_id', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
            ],
        ),
    ]
