# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='temperatures', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='temperature',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
